### ISSUE TITLE
clojure-mode snippets

### ISSUE THREAD

**Issue by dotemacs** [AndreaCrotti/yasnippet-snippets#162] opened 2016-10-07 10:57 UTC
Hello @AndreaCrotti 

thanks for maintaining the collection of snippets.

I noticed that you keep a copy of snippets for clojure mode, while there is also:

https://github.com/mpenet/clojure-snippets maintained by @mpenet

Would you be open to clojure-snippets being a git submodule pointing to @mpenet's repo?

Thanks

**Comment by AndreaCrotti** [comment] 2016-10-07 11:35
Uhm probably not a git submodule @dotemacs because:
- this repo is already a submodule of the yasnippet
- we don't have have any other git submodules here
- this repo is supposed to be something you just use straight away with all contained and consistent.

I would be happy to merge some of the snippets defined there though if they are not here or they are better than the ones we currently have, as long as it's still consistent..

**Comment by mpenet** [comment] 2016-10-07 11:46
It could be a submodule, there's the `--recursive` flag for this. 
Originally the clojure snippets in yas were copied from https://github.com/mpenet/clojure-snippets, so you get updates only if the maintainer manually updates them (copy-pasta), so it would benefit from a being a submodule for sure.

**Comment by dotemacs** [comment] 2016-10-07 12:14
> this repo is already a submodule of the yasnippet

True.

> * we don't have have any other git submodules here
> * this repo is supposed to be something you just use straight away with all contained and consistent.


True, but... What @mpenet said:

> Originally the clojure snippets in yas were copied from https://github.com/mpenet/clojure-snippets, so you get updates only if the maintainer manually updates them (copy-pasta), so it would benefit from a being a submodule for sure.

There was this PR added by me: https://github.com/mpenet/clojure-snippets/pull/8
Which is obviously not in your version of `clojure-snippets`.

I appreciate that you want the user experience to be as easy as possible. But I'd argue that this for Emacs, an editor that you have to configure by editing the setup files. Also, the example above, if somebody tried to use your version of the `clojure-snippets`, they'd experience a bug. So I'd say that this is a more of an inconvenience.

And the task of keeping tabs on who and when a particular snippet directory needs to be updated, who does that fall to?

Not bothered which way we go, as long as everybody agrees on it and the snippets aren't out of sync.

Thanks

**Comment by AndreaCrotti** [comment] 2016-10-07 12:22
@mpenet if the maintainer just raise a pull request here instead of updating its own repo every time the problem is solved, no copy & paste involved..

submodules still require to be updated manually anyway (from me in this case), and to do that I should actually know that something changed and was fixed.

So sorry but I don't think it's a good idea, I'm happy to accept fixes and maintain this collection, but I don't want to add extra complexity for everyone.

**Comment by mpenet** [comment] 2016-10-07 12:30
> @mpenet if the maintainer just raise a pull request here instead of updating its own repo every time the problem is solved, no copy & paste involved..

That's putting burden to the maintainers of all these repos, having to update twice every time ... 

> this repo is already a submodule of the yasnippet

Exactly! So the problem would be solved by just adding a `--recursive` flag to yas git submodule update call. 

Your choice, personally I don't really care since I depend on my repo directly, but your decision/argument is kind of odd tbh.

**Comment by npostavs** [comment] 2016-10-07 12:37
The solution with smallest maintenance burden is to move the updated snippets from mpenet/clojure-snippets to this repo and give @mpenet write access so he can add updates/merge PRs directly.

**Comment by mpenet** [comment] 2016-10-07 12:39
Actually yas already does a --recursive call. So there would be no changes required there either if there were submodules here.

**Comment by dotemacs** [comment] 2016-10-07 12:41
I was about to post this, but @mpenet beat me to it.

The solution @mpenet is advocating is already in place. The only "blocker" is @AndreaCrotti's agreement :)

**Comment by dotemacs** [comment] 2016-10-07 12:42
cc @joaotavora do you have any thoughts on this? Thanks

**Comment by npostavs** [comment] 2016-10-07 12:46
@mpenet @dotemacs Neither of you responded to this point:

> submodules still require to be updated manually anyway

**Comment by AndreaCrotti** [comment] 2016-10-07 12:47
Don't I still have to update the commit hash in .gitmodules to actually make sure it points to the latest revision?
And how do I know that changed and need to update it?

I still honestly would not be too happy to do that unless we actually do it for every mode make a special case for clojure-mode doesn't really make sense to me.
I'd rather just give write access to someone else at that point, even if I don't see why it would be a burden just to raise a PR only here when changes are required (which at least would ensure that someone actually review the changes done).

**Comment by mpenet** [comment] 2016-10-07 12:49
sure: `git submodule update --recursive --remote`

```
This option is only valid for the update command. Instead of using the superproject’s recorded SHA-1 to update the submodule, use the status of the submodule’s remote-tracking branch. The remote used is branch’s remote (branch.<name>.remote), defaulting to origin. The remote branch used defaults to master, but the branch name may be overridden by setting the submodule.<name>.branch option in either .gitmodules or .git/config (with .git/config taking precedence).

```

**Comment by mpenet** [comment] 2016-10-07 12:50
Worse case if you want to do this a bit more manually it's easily scriptable.

**Comment by AndreaCrotti** [comment] 2016-10-07 13:02
Nice didn't know about this feature.
But anyway I don't see the point of making a special case for clojure-mode.

This project has currently 72 different contributors, I've been always happy to merge in improvements and new modes, but I want to make sure that what gets in was at least reviewed.

**Comment by dotemacs** [comment] 2016-10-07 13:11
> But anyway I don't see the point of making a special case for clojure-mode.

1. By 'copy-pasta' you destroy the original contribution credits. In this case @mpenet's.
1. By keeping broken snippets in this repo you'll provide sub par experience for the other Emacs users. And creating working functioning Emacs modes is what this is all about. Right?

> This project has currently 72 different contributors, I've been always happy to merge in improvements and new modes, but I want to make sure that what gets in was at least reviewed.

Well the way you're phrasing it seems to imply that what's being contributed to `clojure-snippets` is somehow not being reviewed before being merged. I honestly don't understand the logic of your argument. If you could elaborate on it a bit more, I'd be very grateful.

Thanks for your time

**Comment by dotemacs** [comment] 2016-10-07 13:19
As for 'special case' see:

https://github.com/magnars/angular-snippets.el
https://github.com/abo-abo/auto-yasnippet
https://github.com/magnars/buster-snippets.el
https://github.com/mrkkrp/common-lisp-snippets
https://github.com/magnars/datomic-snippets
https://github.com/myfreeweb/django-mode

There's more, I can't look for them all now.

**Comment by AndreaCrotti** [comment] 2016-10-07 13:22
1. I'm not copying and pasting anything, if @mpenet proposes his changes only here, he still comes up as contributor..
2. I didn't know they were broken and noone reported it. So sure they have to be fixed but well using an external repo doesn't prevent breaking stuff. And actually making it all automatic makes me not even know if something could have been broken.

And sure it still gets reviewed I'm sure, but I don't get to review it and see if it's consistent with the rest of the snippets.

In terms of all the other interesting snippet collections, well it's very easy for someone to add them to their own configuration, even if they are not here.
This repository is not supposed to have all the possible snippets in the world, but just a good collection that is actually looked after..

**Comment by dotemacs** [comment] 2016-10-07 13:36
Hello @AndreaCrotti 

I want to thank you for your effort for looking after this repo. Open source code is often not appreciated enough.

> This repository is not supposed to have all the possible snippets in the world, but just a good collection that is actually looked after..

I understand that and appreciate it.

[Clojure-mode](https://github.com/AndreaCrotti/yasnippet-snippets/tree/master/clojure-mode) snippets in your repo currently have a bug. The bug was fixed in [clojure-snippets](https://github.com/mpenet/clojure-snippets): mpenet/clojure-snippets#8

> I didn't know they were broken and noone reported it. So sure they have to be fixed but well using an external repo doesn't prevent breaking stuff. And actually making it all automatic makes me not even know if something could have been broken.

I discovered the bug because I loaded `clojure-snippets`. I then provided the fix upstream. I didn't realise that your repo shadowed @mpenet's. My suggestion is to prevent this shadowing.

Maybe the easiest solution is to remove **clojure-mode** from this repo? I don't know.

What do you all think?

Thank you

**Comment by AndreaCrotti** [comment] 2016-10-08 18:59
Good point @dotemacs, I think the shadowing problem should maybe be handled by yasnippet itself.
It's maybe normal to shadow single snippets but probably if you are shadowing snippets for the whole mode without realising it might be an issue..

I could maybe add some documentation about this, for example having this repository always as first in `yas-snippet-dirs` for example.

I would rather fix the issues than deleting current snippets since maybe someone is actually using them..

**Comment by dotemacs** [comment] 2016-10-08 19:55
Hello @AndreaCrotti 

I'm glad that you see the issue here.

There is another potential shadowing, this mode: https://github.com/mrkkrp/common-lisp-snippets probably shadows these snippets in your repo: https://github.com/AndreaCrotti/yasnippet-snippets/tree/master/lisp-mode. Both cover snippets for Lisp.

> I could maybe add some documentation about this, for example having this repository always as first in yas-snippet-dirs for example.

Maybe. But what if people see the snippets in your repo and don't find out about @mpenet's clojure-snippets repo and decide to create more snippets for Clojure in particular. But only later to learn that @mpenet's repo already has them? How do we avoid that potential issue?

> I would rather fix the issues than deleting current snippets since maybe someone is actually using them..

Just to be sure, I'm went through all the snippets for clojure and reported which ones aren't the same. See [this gist](https://gist.github.com/dotemacs/4fba0f2325b87a68cd3736c480a78ce1)

**y** - means: yes, it exists
**x** - means: no, the snippet does not exist

The ones that do exist in both repos do match by key and name!

I think that fixing this is to have one authoritative source of the snippets. 

It took me time to go through all the snippets to point out which ones match or don't.

Who wants to do that manually? For all the modes? All the time going forward?

**Comment by dotemacs** [comment] 2016-10-08 20:00
My point here was that if you want to fix this, the easiest solution is to follow the steps as pointed at by @mpenet. 

As for anybody else using them, my table is meant to reassure you that this could not be the case. Because they would have outdated or buggy clojure snippets.

**Comment by AndreaCrotti** [comment] 2016-10-08 22:38
Thanks for the work but there is not such a thing as an authoritative repo to be honest.

As far as I could know there could be 100 other repositories of clojure-mode snippets, differing in many ways, am I supposed to merge all of them?
So I agree that the shadowing is an issue but don't agree with the solution, I'm not going to add submodules to this repository since it's just easier for everyone to have one authoritative source (even if sure I'll have a look at the few bugs to fix).

Closing this for now sorry we can discuss about the shadowing in another issue if you want (even if in this repo there might not be so much I can do about it).

**Closed by AndreaCrotti** 2016-10-08 22:38 UTC

**Comment by dotemacs** [comment] 2016-10-08 23:20
> Thanks for the work but there is not such a thing as an authoritative repo to be honest.

Considering that your repo gets pulled in by default when **yasnippets** is installed, your repo is pretty much the authoritative repo by default.

> As far as I could know there could be 100 other repositories of clojure-mode snippets, differing in many ways, am I supposed to merge all of them?

No, but if you pick one that is up to date and actively maintained you'd be pretty much solving the problem.

The repo in question is in MELPA & MELPA Stable, actively maintained by a person who develops in Clojure. I honestly don't see one negative issue there.

> So I agree that the shadowing is an issue but don't agree with the solution, I'm not going to add submodules to this repository since it's just easier for everyone to have one authoritative source (even if sure I'll have a look at the few bugs to fix).

You can still have what you describe: "one authoritative source". Nothing is being blocked/omitted by @mpenet suggestion with the use of git submodule.

I just hope that this approach doesn't put people off. See [this email](https://groups.google.com/forum/#!topic/smart-snippet/HI4T9_bybgo). Granted, it's from a year ago, but the user wants to **remove the default snippets** as (s)he finds them outdated.

In any case, thank you.
